# Data configuration for Indian Equity ML Platform

market: nse

data_source: yfinance

start_date: "2000-01-01"
end_date: null
incremental_update: true
refresh_overlap_days: 10

tickers:

  # Information Technology
  - TCS.NS
  - INFY.NS
  - HCLTECH.NS
  - WIPRO.NS
  - TECHM.NS

  # Banking & Financial Services
  - HDFCBANK.NS
  - ICICIBANK.NS
  - SBIN.NS
  - AXISBANK.NS
  - KOTAKBANK.NS

  # Index Funds
  - ^NSEI



data_directory: data/raw

frequency: 1d

adjusted_prices: true
